---
- hosts: webserver
  become: yes
  tasks:
  - name:  install jdk on ubuntu18 node1
    apt:
     name: "{{myjavaonubuntu}}"
     state: latest
    when: ansible_os_family == "Debian"

  - name: install jdk8 on amazonlinux2 node2
    yum:
     name: "{{myjavaonamazonos}}"
     state: present
    when: ansible_os_family == "RedHat"