---
- hosts: webserver
  become: yes
  vars:
    myvar1: raj
    myvar2: shekar
  tasks:
  - name: dispaly myvar1
    debug:
      msg: "{{myvar1}}"

  - name: dispaly myvar2
    debug:
      msg: "{{myvar2}}"